module Constants

  IN_PROGRESS_STATES =  ["CREATE_IN_PROGRESS","ROLLBACK_IN_PROGRESS","DELETE_IN_PROGRESS","UPDATE_IN_PROGRESS","UPDATE_COMPLETE_CLEANUP_IN_PROGRESS","UPDATE_ROLLBACK_IN_PROGRESS","UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS"]
  SUCCESS_END_STATES  = ["CREATE_COMPLETE", "UPDATE_COMPLETE"]
  FAILURE_END_STATES = ["CREATE_FAILED", "DELETE_FAILED", "UPDATE_ROLLBACK_FAILED", "ROLLBACK_COMPLETE","ROLLBACK_FAILED","UPDATE_ROLLBACK_COMPLETE"]
  END_STATES = SUCCESS_END_STATES + FAILURE_END_STATES
  ALL_STATES = IN_PROGRESS_STATES + END_STATES
  AWS_SDK_POLL_INTERVAL_IN_SECONDS = 30
  EC2_IN_PROGRESS_STATES = ["PENDING", "SHUTTING-DOWN", "STOPPING"]
  EC2_TERMINATED_STATE = "TERMINATED"
  EC2_STOPPED_STATES = [ EC2_TERMINATED_STATE, "STOPPED"]
  EC2_RUNNING_STATES = ["RUNNING"]
  EC2_END_STATES = EC2_STOPPED_STATES + EC2_RUNNING_STATES
  EC2_ALL_STATES = EC2_IN_PROGRESS_STATES + EC2_STOPPED_STATES + EC2_RUNNING_STATES

  class << self

    def root_folder
      File.absolute_path("#{File.dirname(__FILE__)}/..")
    end

  end

end
