module Constants
  IN_PROGRESS_STATES =  ["CREATE_IN_PROGRESS","ROLLBACK_IN_PROGRESS","DELETE_IN_PROGRESS","UPDATE_IN_PROGRESS","UPDATE_COMPLETE_CLEANUP_IN_PROGRESS","UPDATE_ROLLBACK_IN_PROGRESS","UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS"]
  SUCCESS_END_STATES  = ["CREATE_COMPLETE", "UPDATE_COMPLETE"]
  FAILURE_END_STATES = ["CREATE_FAILED", "DELETE_FAILED", "UPDATE_ROLLBACK_FAILED", "ROLLBACK_COMPLETE","ROLLBACK_FAILED","UPDATE_ROLLBACK_COMPLETE"]
  END_STATES = SUCCESS_END_STATES + FAILURE_END_STATES
  ALL_STATES = IN_PROGRESS_STATES + END_STATES
  RED_COLOR = "\033[01;31m"
  RESET_COLOR = "\033[00m"
  GREEN_COLOR = "\033[32m"
  BLUE_COLOR = "\033[34m"
  PURPLE_COLOUR = "\033[01;35m"
  YELLOW_COLOR = "\033[0;33m"
end
