require 'rake'
require 'cloudformation_stack'
require 'json'

namespace :example do
  desc 'Deploying a cloudformation template with params using AWS profile as authentication method'
  task :deploy_with_aws_profile, [:aws_profile, :region, :keyname, :instance_type, :image_id, :timeout] do |t, args|
    cf_template_parameters = {
      ImageId: args[:image_id],
      InstanceType: args[:instance_type],
      KeyName: args[:keyname]
    }
    cf_stack_name = "sample-stack"
    cf_template_body = File.read('sample_cf.template')
    credential_params = {
      mode: 'aws_profile',
      profile_name: args[:aws_profile]
    }
    disable_rollback = true
    cf_stack = CFStackService.new(cf_stack_name, cf_template_body, cf_template_parameters, credential_params, args[:region])
    cf_stack.deploy(disable_rollback,args[:timeout])
  end

  desc 'Deploying a cloudformation template with params using IAM role as authentication method'
  task :deploy_with_iam_role, [:iam_role_arn, :region, :keyname, :instance_type, :image_id, :timeout] do |t, args|
    cf_template_parameters = {
      ImageId: args[:image_id],
      InstanceType: args[:instance_type],
      KeyName: args[:keyname]
    }
    cf_stack_name = "sample-stack"
    cf_template_body = File.read('sample_cf.template')
    credential_params = {
      mode: 'iam_role_arn',
      iam_role_arn: args[:iam_role_arn]
    }
    disable_rollback = true
    cf_stack = CFStackService.new(cf_stack_name, cf_template_body, cf_template_parameters, credential_params, args[:region])
    cf_stack.deploy(disable_rollback,args[:timeout])
  end

  desc 'Deploying a cloudformation template with params using AWS access key as authentication method'
  task :deploy_with_access_key, [:region, :keyname, :instance_type, :image_id, :timeout, :access_key_id, :secret_access_key, :session_token] do |t, args|
    cloudformation_parameters = {
      ImageId: args[:image_id],
      InstanceType: args[:instance_type],
      KeyName: args[:keyname]
    }
    cf_stack_name = "sample-stack"
    cf_template_body = File.read('sample_cf.template')
    credential_params = {
      mode: 'aws_access_key',
      access_key_id: args[:access_key_id], # No need to pass it, if ENV['AWS_ACCESS_KEY_ID']
      secret_access_key: args[:secret_access_key], # No need to pass it, if ENV['AWS_SECRET_ACCESS_KEY']
      session_token: args[:session_token] # No need to pass it, if ENV['AWS_SESSION_TOKEN']
    }
    disable_rollback = true
    cf_stack = CFStackService.new(cf_stack_name, cf_template_body, cf_template_parameters, credential_params, args[:region])
    cf_stack.deploy(disable_rollback,args[:timeout])
  end
end
